# Generated by Django 3.2.4 on 2021-06-24 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('text', models.TextField(max_length=300, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='MemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('username', models.CharField(max_length=80, verbose_name='یوزرنیم')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=60, verbose_name='پسورد')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید ۱۱ رقم(اعداد انگلیسی) و به فرم 09XXXXXXXXX باشد.', regex='^(09\\d{9})$')], verbose_name='شماره تلفن')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'کاربر خاطره نگار',
                'verbose_name_plural': 'کابر های خاطره نگار',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('text', models.TextField(max_length=300, verbose_name='متن')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
                ('tagged_people', models.ManyToManyField(related_name='post_where_tagged', to='memoreminder.MemoUser', verbose_name='افراد تگ شده در خاطره')),
            ],
            options={
                'verbose_name': 'خاطره',
                'verbose_name_plural': 'خاطره ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('memo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.post', verbose_name='خاطره')),
            ],
            options={
                'verbose_name': 'لایک برای پست',
                'verbose_name_plural': 'لایک های پست ها',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='memoreminder.Tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.comment', verbose_name='کامنت')),
                ('memo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک برای کامنت',
                'verbose_name_plural': 'لایک های کامنت ها',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='memo_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.post', verbose_name='خاطره'),
        ),
    ]
