# Generated by Django 3.2.4 on 2021-06-24 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('username', models.CharField(max_length=80, verbose_name='یوزرنیم')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('email', models.CharField(max_length=60, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید ۱۱ رقم(اعداد انگلیسی) و به فرم 09XXXXXXXXX باشد.', regex='^(09\\d{9})$')], verbose_name='شماره تلفن')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
