# Generated by Django 3.2.4 on 2021-06-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memouser',
            options={'verbose_name': 'کاربر خاطره نگار', 'verbose_name_plural': 'کابر های خاطره نگار'},
        ),
        migrations.AddField(
            model_name='memouser',
            name='password',
            field=models.CharField(default=1234, max_length=60, verbose_name='پسورد'),
            preserve_default=False,
        ),
    ]
