# Generated by Django 3.2.4 on 2021-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0002_auto_20210624_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memouser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
    ]
