# Generated by Django 3.2.4 on 2021-06-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0003_alter_memouser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('text', models.TextField(max_length=300, verbose_name='متن')),
                ('memo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.comment', verbose_name='کامنت')),
                ('memo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.memouser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک برای کامنت',
                'verbose_name_plural': 'لایک های کامنت ها',
            },
        ),
    ]
