# Generated by Django 3.2.4 on 2021-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='memouser',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='توکن'),
        ),
    ]
