# Generated by Django 3.2.4 on 2021-07-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0005_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='memouser',
            name='accounts',
            field=models.ManyToManyField(related_name='_memoreminder_memouser_accounts_+', to='memoreminder.MemoUser', verbose_name='دوست ها'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید'), ('rejected', 'رد'), ('pending', 'در حال بررسی')], default='pending', max_length=50, verbose_name='وضعیت'),
        ),
    ]
