# Generated by Django 3.2.4 on 2021-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0006_auto_20210706_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memouser',
            name='accounts',
        ),
        migrations.AddField(
            model_name='memouser',
            name='friends',
            field=models.ManyToManyField(related_name='_memoreminder_memouser_friends_+', to='memoreminder.MemoUser', verbose_name='دوست ها'),
        ),
    ]
