# Generated by Django 3.2.4 on 2021-07-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0007_auto_20210706_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memouser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_memoreminder_memouser_friends_+', to='memoreminder.MemoUser', verbose_name='دوست ها'),
        ),
    ]
