# Generated by Django 3.2.4 on 2021-07-15 09:44

from django.db import migrations, models
import django.db.models.deletion
import memoreminder.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0008_alter_memouser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('file', models.FileField(blank=True, null=True, upload_to=memoreminder.helpers.OnUploadRename('post/'), verbose_name='فایل')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoreminder.post', verbose_name='خاطره')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
    ]
