# Generated by Django 3.2.4 on 2021-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0009_postfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_where_tagged', to='memoreminder.MemoUser', verbose_name='افراد تگ شده در خاطره'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='memoreminder.Tag', verbose_name='تگ ها'),
        ),
    ]
