# Generated by Django 3.2.4 on 2021-07-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0012_postfile_file_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.CharField(choices=[('private', 'خصوصی'), ('public', 'عمومی')], default='public', max_length=50, verbose_name='حالت'),
        ),
    ]
