# Generated by Django 3.2.4 on 2021-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoreminder', '0013_auto_20210720_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memouser',
            name='password',
            field=models.CharField(max_length=200, verbose_name='پسورد'),
        ),
    ]
